name: superbuild-and-test

on:  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Debug

jobs:
  build_windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: clone bat2exe
      run: git clone https://github.com/islamadel/bat2exe.git
      
    - name: Copy bat2exec script
      run: copy run_executable.bat ..\install_Windows\bin

    - name: run bat2exec and create vr-volumeviewer executable
      # 
      run: |
           cd superbuild\bat2exe\upload 
           bat2exe.exe superbuild\install_Windows\bin superbuild\install_Windows\bin

    