name: superbuild-and-bat3exe-test

on:  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build_windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: Clean superbuild folder
      run: superbuild/clean/clean.bat
      
    - name: Open superbuild folder
      run: cd superbuild

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
           cd superbuild 
           cmake -S . -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    - name: Build
      # Build your program with the given configuration
      run: |
           cd superbuild
           ninja
    - name: clone bat2exe
      run: |
           cd superbuild
           git clone https://github.com/islamadel/bat2exe.git
      
    - name: Copy bat2exec script
      run: |
           cd superbuild\executables
           copy run_executable.bat ..\install_Windows\bin
    - name: run bat2exec and create vr-volumeviewer executable 
      run: |
           cd superbuild\bat2exe\upload 
           bat2exe.exe bat2exe.exe  /source:C:\Users\Kmilo\Documents\VR-Volumeviewer\superbuild\install_Windows /target:C:\Users\Kmilo\Documents\VR-Volumeviewer\superbuild\install_Windows /s /y
    - name: Test
      working-directory: ${{github.workspace}}/superbuild/install_Windows/bin
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run:  ctest
