# This is a basic workflow to help you get started with Actions

name: Download Visual studio Redistributables

# Controls when the workflow will run
on:  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: suisei-cn/actions-download-file@v1
       id: vc_distributablex64
       name: Download the file
       with:
          url: https://aka.ms/vs/17/release/vc_redist.x64.exe
          target: ${{github.workspace}}/superbuild/install_Windows/bin
          auto-match: true
     - uses: actions/upload-artifact@v2
       with:
         name: vc_redist.x64.exe
         path: ${{github.workspace}}/superbuild/install_Windows/bin/vc_redist.x64.exe
