name: build-vr-volumeviewer-linux

on:  workflow_dispatch

env:
  BUILD_TYPE: Debug

jobs:
  build_linux:
   
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    #- name: Install OpenGL support
    #  uses: openrndr/setup-opengl@v1.1
    #- name: Test OpenGL
    #  run: xvfb-run glxinfo
    - name: Run build script
      run: sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
      shell: bash
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.3'
    
    - name: Clean superbuild folder
      run: python3 superbuild/clean/clean.py
      
    - name: Open superbuild folder
      run: cd superbuild
    
    - name: Install Mesa Packages
      run: |
          sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev libgl-dev


    - name: Configure CMake
      run: |
           cd superbuild 
           cmake -S . -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
           cd superbuild
           make
    - uses: papeloto/action-zip@v1
      with:
        files: superbuild/install_Linux/bin
        recursive: false
        dest: superbuild/install_Linux/vr-volumeviewer-linux.zip
    - name: Upload app to release - MacOS
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/superbuild/install_Linux/vr-volumeviewer-linux.zip
        tag: ${{ github.ref }}
    - name: Test
      working-directory: ${{github.workspace}}/superbuild/install_Linux/bin
      run:  ctest
