name: build-vr-volumeviewer-linux

on:  workflow_dispatch

env:
  BUILD_TYPE: Debug

jobs:
  build_mac:
   
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.3'
    
    - name: Clean superbuild folder
      run: python3 superbuild/clean/clean.py
      
    - name: Open superbuild folder
      run: cd superbuild

    - name: Configure CMake
      run: |
           cd superbuild 
           cmake -S . -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
           cd superbuild
           make
    - name: Test
      working-directory: ${{github.workspace}}/superbuild/install_Linux/bin
      run:  ctest