name: build-release-vr-volumeviewer

on:  
  push:
    tags:
      - '*'

env:
  BUILD_TYPE: Release
jobs:
  build_windows:
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    

    - name: Clean superbuild folder
      run: superbuild/clean/clean.bat
      
    - name: Open superbuild folder
      run: cd superbuild

    - name: Configure CMake
      run: |
           cd superbuild 
           cmake -S . -B . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    - name: Build
      run: |
           cd superbuild
           ninja
    - name: clone bat2exe
      run: |
           cd superbuild
           git clone https://github.com/islamadel/bat2exe.git
      
    - name: Copy bat2exec script to create .exe
      shell: cmd
      run: copy superbuild\scripts\CCV_VR_VWR.bat superbuild\install_Windows\bin
    - name: List files on bin folder
      run: |
           cd superbuild\install_Windows\bin
           dir
    - name: run bat2exec in the background and create vr-volumeviewer executable 
      shell: cmd
      run: superbuild\scripts\execute_bat2exe_background.bat ${{github.workspace}}
    - name: Upload app to release - windows
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}\superbuild\install_Windows\bin\CCV_VR_VWR.exe
        tag: ${{ github.ref }}
        prerelease: true
